version: '2'
services:
  app:
    build: .
    ports:
    - "8000:8000"
    working_dir: /usr/src/blog
    volumes:
    - ./blog:/usr/src/blog
    links:
    - mongodb
    tty: true
  mongodb:
    image: mongo:latest
    container_name: "mongo-blog"
    environment:
      - MONGO_DATA_DIR=/data/configdb
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./blog/db:/data/configdb
    ports:
    - "27017:27017"
    restart: always